import { ACTION_TYPE } from '../action.config';

export const FETCH_SPECIAL_DEAL_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_SPECIAL_DEAL_LIST`;
export const FETCH_SPECIAL_DEAL = `${ACTION_TYPE.API_ACTION}/FETCH_SPECIAL_DEAL`;

export const CLEAR_DATA_SPECIAL_DEAL_LIST = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_SPECIAL_DEAL_LIST`;
export const CLEAR_DATA_SPECIAL_DEAL = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_SPECIAL_DEAL`;
