import { ACTION_TYPE } from '../action.config';

export const ADD_DISCUSSION = `${ACTION_TYPE.API_ACTION}/ADD_DISCUSSION`;
export const ADD_DISCUSSION_COMMENT = `${ACTION_TYPE.API_ACTION}/ADD_DISCUSSION_COMMENT`;
export const EDIT_DISCUSSION = `${ACTION_TYPE.API_ACTION}/EDIT_DISCUSSION`;
export const FETCH_DISCUSSIONS_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_DISCUSSIONS_BOXES`;
export const CLEAR_DATA_DISCUSSIONS_BOXES = `${ACTION_TYPE.BACKGROUND_ACTION}/CLEAR_DATA_DISCUSSIONS_BOXES`;
