import { ACTION_TYPE } from './action.config';

export const DISPLAY_CART_SUMMARY = `${ACTION_TYPE.INTERACTION_ACTION}/DISPLAY_CART_SUMMARY`;

export const GET_CART = `${ACTION_TYPE.API_ACTION}/GET_CART`;
export const GET_CART_GIFT = `${ACTION_TYPE.API_ACTION}/GET_CART_GIFT`;
export const ADD_TO_CART = `${ACTION_TYPE.API_ACTION}/ADD_TO_CART`;
export const REMOVE_FROM_CART = `${ACTION_TYPE.API_ACTION}/REMOVE_FROM_CART`;
export const ADD_DISCOUNT_CODE = `${ACTION_TYPE.API_ACTION}/ADD_DISCOUNT_CODE`;
export const REMOVE_DISCOUNT_CODE = `${ACTION_TYPE.API_ACTION}/REMOVE_DISCOUNT_CODE`;
export const FETCH_ADD_ON_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_ADD_ON_LIST`;
export const FETCH_CART_REDEEM_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_CART_REDEEM_BOXES`;
export const CLEAR_CART = `${ACTION_TYPE.INTERACTION_ACTION}/CLEAR_CART`;

export const CHECKOUT_DELIVERY_CHOOSE_ADDRESS = `${ACTION_TYPE.INTERACTION_ACTION}/CHECKOUT_DELIVERY_CHOOSE_ADDRESS`;
export const CHECKOUT_DELIVERY_GUEST_ADDRESS = `${ACTION_TYPE.INTERACTION_ACTION}/CHECKOUT_DELIVERY_GUEST_ADDRESS`;
export const CHECKOUT_DELIVERY_USER_PICKUP_STORE_ADDRESS = `${ACTION_TYPE.INTERACTION_ACTION}/CHECKOUT_DELIVERY_USER_PICKUP_STORE_ADDRESS`;
export const CHECKOUT_DELIVERY_SET_GIFT_MESSAGE = `${ACTION_TYPE.INTERACTION_ACTION}/CHECKOUT_DELIVERY_SET_GIFT_MESSAGE`;
export const CHECKOUT_DELIVERY_SET_NOTE_MESSAGE = `${ACTION_TYPE.INTERACTION_ACTION}/CHECKOUT_DELIVERY_SET_NOTE_MESSAGE`;
export const CHECKOUT_DELIVERY_SET_DELIVERY_METHOD = `${ACTION_TYPE.INTERACTION_ACTION}/CHECKOUT_DELIVERY_SET_DELIVERY_METHOD`;
export const CHECKOUT_CLEAR_DELIVERY_CONFIG = `${ACTION_TYPE.INTERACTION_ACTION}/CHECKOUT_CLEAR_DELIVERY_CONFIG`;

export const CHECKOUT = `${ACTION_TYPE.API_ACTION}/CHECKOUT`;
export const PAYMENT = `${ACTION_TYPE.API_ACTION}/PAYMENT`;
export const PAYMENT_SUCCESS = `${ACTION_TYPE.API_ACTION}/PAYMENT_SUCCESS`;
export const SELECT_GIFT = `${ACTION_TYPE.INTERACTION_ACTION}/SELECT_GIFT`;
export const FETCH_BOXES_TO_FREESHIP = `${ACTION_TYPE.INTERACTION_ACTION}/FETCH_BOXES_TO_FREESHIP`;
export const FETCH_CONSTANTS = `${ACTION_TYPE.API_ACTION}/FETCH_CONSTANTS`;
export const CHECK_SAME_DAY_SHIPPING = `${ACTION_TYPE.INTERACTION_ACTION}/CHECK_SAME_DAY_SHIPPING`;
export const FETCH_SUGGESTION_DISCOUNT_CODES = `${ACTION_TYPE.INTERACTION_ACTION}/FETCH_SUGGESTION_DISCOUNT_CODES`;
export const CHECKOUT_ADDRESS = `${ACTION_TYPE.API_ACTION}/CHECKOUT_ADDRESS`;
export const FETCH_STORES = `${ACTION_TYPE.API_ACTION}/FETCH_STORES`;
export const FETCH_SAMPLE_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_SAMPLE_BOXES`;
