import { ACTION_TYPE } from './action.config';

export const FETCH_DISCOUNT_CODE = `${ACTION_TYPE.API_ACTION}/FETCH_DISCOUNT_CODE`;
export const FETCH_DISCOUNT_CODE_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_DISCOUNT_CODE_BOXES`;
export const CLEAR_DATA_DISCOUNT_CODE = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_DISCOUNT_CODE`;
