import { ACTION_TYPE } from './action.config';

export const LOAD_GAME = `${ACTION_TYPE.API_ACTION}/LOAD_GAME`;
export const GET_USER_GIFT = `${ACTION_TYPE.API_ACTION}/GET_USER_GIFT`;
export const GET_TODAY_GIFT = `${ACTION_TYPE.API_ACTION}/GET_TODAY_GIFT`;
export const PLAY_GAME = `${ACTION_TYPE.API_ACTION}/PLAY_GAME`;
