import { ACTION_TYPE } from './action.config';

export const LIKE_PRODUCT = `${ACTION_TYPE.API_ACTION}/LIKE_PRODUCT`;
export const UN_LIKE_PRODUCT = `${ACTION_TYPE.API_ACTION}/UN_LIKE_PRODUCT`;
export const FETCH_LIKED_BOX_ID = `${ACTION_TYPE.API_ACTION}/FETCH_LIKED_BOX_ID`;
export const FETCH_LIKED_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_LIKED_BOXES`;
