import { ACTION_TYPE } from './action.config';

export const FETCH_LOVE_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_LOVE_LIST`;
export const GET_LOVE_DETAIL = `${ACTION_TYPE.API_ACTION}/GET_LOVE_DETAIL`;
export const ADD_LOVE = `${ACTION_TYPE.API_ACTION}/ADD_LOVE`;
export const GET_LOVE_BOX = `${ACTION_TYPE.API_ACTION}/GET_LOVE_BOX`;
