import { ACTION_TYPE } from './action.config';

export const FETCH_MAGAZINE_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_MAGAZINE_LIST`;
export const FETCH_MAGAZINE_DASHBOARD = `${ACTION_TYPE.API_ACTION}/FETCH_MAGAZINE_DASHBOARD`;
export const FETCH_MAGAZINE_CATEGORY = `${ACTION_TYPE.API_ACTION}/FETCH_MAGAZINE_CATEGORY`;
export const FETCH_MAGAZINE_TAG = `${ACTION_TYPE.API_ACTION}/FETCH_MAGAZINE_TAG`;

export const FETCH_MAGAZINE_BY_SLUG = `${ACTION_TYPE.API_ACTION}/FETCH_MAGAZINE_BY_SLUG`;
export const FETCH_MAGAZINE_RELATED_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_MAGAZINE_RELATED_BOXES`;
export const FETCH_MAGAZINE_RELATED_BLOGS = `${ACTION_TYPE.API_ACTION}/FETCH_MAGAZINE_RELATED_BLOGS`;

export const FETCH_MAGAZINE_BY_KEYWORD = `${ACTION_TYPE.API_ACTION}/FETCH_MAGAZINE_BY_KEYWORD`;

export const CLEAR_DATA_MAGAZINE_LIST = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_MAGAZINE_LIST`;
export const CLEAR_DATA_MAGAZINE = `${ACTION_TYPE.BACKGROUND_ACTION}/CLEAR_DATA_MAGAZINE`;
