import { ACTION_TYPE } from './action.config';

export const OPEN_MODAL = `${ACTION_TYPE.INTERACTION_ACTION}/OPEN_MODAL`;
export const CLOSE_MODAL = `${ACTION_TYPE.INTERACTION_ACTION}/CLOSE_MODAL`;
export const PUSH_STATE_WHEN_OPENING_MODAL = `${ACTION_TYPE.INTERACTION_ACTION}/PUSH_STATE_WHEN_OPENING_MODAL`;
export const BACK_STATE_WHEN_CLOSING_MODAL = `${ACTION_TYPE.INTERACTION_ACTION}/BACK_STATE_WHEN_CLOSING_MODAL`;
