import { ACTION_TYPE } from './action.config';

export const FETCH_ORDER = `${ACTION_TYPE.API_ACTION}/FETCH_ORDER`;
export const FETCH_CANCEL_ORDER_REASON = `${ACTION_TYPE.API_ACTION}/FETCH_CANCEL_ORDER_REASON`;
export const CANCEL_ORDER = `${ACTION_TYPE.API_ACTION}/CANCEL_ORDER`;
