import { ACTION_TYPE } from './action.config';

export const FETCH_PROVINCE_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_PROVINCE_LIST`;
export const FETCH_SHIPPING_FEE_BY_DISTRICT_ID = `${ACTION_TYPE.API_ACTION}/FETCH_SHIPPING_FEE_BY_DISTRICT_ID`;
export const FETCH_WARD_BY_PROVINCE_ID = `${ACTION_TYPE.API_ACTION}/FETCH_WARD_BY_PROVINCE_ID`;
