import { ACTION_TYPE } from './action.config';

export const SEARCH_ALL = `${ACTION_TYPE.API_ACTION}/SEARCH_ALL`;
export const SEARCH_SUGGESTION = `${ACTION_TYPE.API_ACTION}/SEARCH_SUGGESTION`;
export const SEARCH_SUGGESTION_SELECT = `${ACTION_TYPE.INTERACTION_ACTION}/SEARCH_SUGGESTION_SELECT`;
export const CLEAR_DATA_SEARCH = `${ACTION_TYPE.BACKGROUND_ACTION}/CLEAR_DATA_SEARCH`;
