import { ACTION_TYPE } from './action.config';

export const FETCH_THEME = `${ACTION_TYPE.API_ACTION}/FETCH_THEME`;
export const FETCH_PRODUCT_BY_THEME_ID = `${ACTION_TYPE.API_ACTION}/FETCH_PRODUCT_BY_THEME_ID`;
export const CLEAR_DATA_PRODUCT_BY_THEME_ID = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_PRODUCT_BY_THEME_ID`;
