import { ACTION_TYPE } from './action.config';

export const FETCH_USER_DASHBOARD = `${ACTION_TYPE.API_ACTION}/FETCH_USER_DASHBOARD`;

export const FETCH_USER_ORDER_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_USER_ORDER_LIST`;
export const FETCH_USER_WATCHED_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_USER_WATCHED_LIST`;
export const FETCH_USER_WAIT_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_USER_WAIT_LIST`;
export const FETCH_USER_ADDRESS_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_USER_ADDRESS_LIST`;
export const FETCH_USER_TRANSACTION_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_USER_TRANSACTION_LIST`;

export const FETCH_USER_PROFILE = `${ACTION_TYPE.API_ACTION}/FETCH_USER_PROFILE`;
export const EDIT_USER_PROFILE = `${ACTION_TYPE.API_ACTION}/EDIT_USER_PROFILE`;
export const CHANGE_PASSWORD_USER = `${ACTION_TYPE.API_ACTION}/CHANGE_PASSWORD_USER`;

export const CHANGE_AVATAR_USER = `${ACTION_TYPE.API_ACTION}/CHANGE_AVATAR_USER`;
export const CLEAR_USER_STORE = `${ACTION_TYPE.BACKGROUND_ACTION}/CLEAR_USER_STORE`;

export const FETCH_USER_REFERRER_PROFILE = `${ACTION_TYPE.API_ACTION}/FETCH_USER_REFERRER_PROFILE`;

export const UPDATE_GUEST_PASSWORD = `${ACTION_TYPE.API_ACTION}/UPDATE_GUEST_PASSWORD`;
export const SHARE_EMAIL = `${ACTION_TYPE.API_ACTION}/SHARE_EMAIL`;

export const CHECK_BIRTHDAY = `${ACTION_TYPE.API_ACTION}/CHECK_BIRTHDAY`;
export const SET_BIRTHDAY = `${ACTION_TYPE.API_ACTION}/SET_BIRTHDAY`;

export const CLEAR_DATA_USER_DASHBOARD = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_USER_DASHBOARD`;
export const CLEAR_DATA_USER_REFERRER_PROFILE = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_USER_REFERRER_PROFILE`;
export const CLEAR_DATA_USER_ORDER_LIST = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_USER_ORDER_LIST`;
export const CLEAR_DATA_USER_WATCHED_LIST = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_USER_WATCHED_LIST`;
export const CLEAR_DATA_USER_WAIT_LIST = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_USER_WAIT_LIST`;
export const CLEAR_DATA_USER_ADDRESS_LIST = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_USER_ADDRESS_LIST`;
export const CLEAR_DATA_USER_TRANSACTION_LIST = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_USER_TRANSACTION_LIST`;
