import { ACTION_TYPE } from '../action.config';

export const FETCH_FAQ_TOPIC_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_FAQ_TOPIC_LIST`;
export const FETCH_FAQ_ARTICLE_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_FAQ_ARTICLE_LIST`;
export const GET_FAQ_ARTICLE_DETAIL = `${ACTION_TYPE.API_ACTION}/GET_FAQ_ARTICLE_DETAIL`;
