import { ACTION_TYPE } from '../action.config';

export const FETCH_REFERRAL_SCHEMES = `${ACTION_TYPE.API_ACTION}/FETCH_REFERRAL_SCHEMES`;
export const FETCH_REFERRAL_SCHEME_DETAIL = `${ACTION_TYPE.API_ACTION}/FETCH_REFERRAL_SCHEME_DETAIL`;
export const FETCH_REFERRAL_SCHEME_VALIDATED_DETAIL = `${ACTION_TYPE.API_ACTION}/FETCH_REFERRAL_SCHEME_VALIDATED_DETAIL`;
export const FETCH_REFERRAL_SCHEMES_SHARE_LINK = `${ACTION_TYPE.API_ACTION}/FETCH_REFERRAL_SCHEMES_SHARE_LINK`;
export const FETCH_REFERRAL_SCHEME_SHARE_LINK = `${ACTION_TYPE.API_ACTION}/FETCH_REFERRAL_SCHEME_SHARE_LINK`;
export const FETCH_REFERRAL_STATISTICS_AND_HISTORY = `${ACTION_TYPE.API_ACTION}/FETCH_REFERRAL_STATISTICS_AND_HISTORY`;
export const FETCH_REFEREE_SCHEMES_BY_CODE = `${ACTION_TYPE.API_ACTION}/FETCH_REFEREE_SCHEMES_BY_CODE`;
export const FETCH_REFEREE_SCHEME_BY_CODE = `${ACTION_TYPE.API_ACTION}/FETCH_REFEREE_SCHEME_BY_CODE`;
export const APPLY_REFERRAL_CODE = `${ACTION_TYPE.API_ACTION}/APPLY_REFERRAL_CODE`;
