import { ACTION_TYPE } from '../action.config';

export const SIGN_IN = `${ACTION_TYPE.API_ACTION}/SIGN_IN`;
export const SIGN_IN_LOCAL = `${ACTION_TYPE.INTERACTION_ACTION}/SIGN_IN_LOCAL`;
export const SIGN_IN_WITH_TOKEN = `${ACTION_TYPE.API_ACTION}/SIGN_IN_WITH_TOKEN`;
export const SIGN_IN_FB = `${ACTION_TYPE.API_ACTION}/SIGN_IN_FB`;
export const SIGN_IN_WITH_APPLE_ID = `${ACTION_TYPE.API_ACTION}/SIGN_IN_WITH_APPLE_ID`;
export const SET_APPLE_SIGNIN_STATE = `${ACTION_TYPE.INTERACTION_ACTION}/SET_APPLE_SIGNIN_STATE`;
export const SIGNIN_WITH_GOOGLE = `${ACTION_TYPE.API_ACTION}/SIGNIN_WITH_GOOGLE`;
export const SET_GOOGLE_SIGNIN_STATE = `${ACTION_TYPE.INTERACTION_ACTION}/SET_GOOGLE_SIGNIN_STATE`;
export const SET_FACEBOOK_SIGNIN_STATE = `${ACTION_TYPE.INTERACTION_ACTION}/SET_FACEBOOK_SIGNIN_STATE`;
export const LINK_SOCIAL_ACCOUNT = `${ACTION_TYPE.API_ACTION}/LINK_SOCIAL_ACCOUNT`;
export const UNLINK_SOCIAL_ACCOUNT = `${ACTION_TYPE.API_ACTION}/UNLINK_SOCIAL_ACCOUNT`;
export const SIGN_OUT = `${ACTION_TYPE.API_ACTION}/SIGN_OUT`;
export const CLEANUP_SESSION = `${ACTION_TYPE.INTERACTION_ACTION}/CLEANUP_SESSION`;
export const SIGN_UP = `${ACTION_TYPE.API_ACTION}/SIGN_UP`;
export const FAST_TRACK_REQUEST_OTP = `${ACTION_TYPE.API_ACTION}/FAST_TRACK_REQUEST_OTP`;
export const FAST_TRACK_VERIFY_OTP = `${ACTION_TYPE.API_ACTION}/FAST_TRACK_VERIFY_OTP`;
export const FETCH_USER_PROFILE = `${ACTION_TYPE.API_ACTION}/FETCH_USER_PROFILE`;

export const EDIT_USER_PROFILE = `${ACTION_TYPE.API_ACTION}/EDIT_USER_PROFILE`;
export const CHANGE_AVATAR_USER = `${ACTION_TYPE.API_ACTION}/CHANGE_AVATAR_USER`;
export const FORGOT_PASSWORD = `${ACTION_TYPE.API_ACTION}/FORGOT_PASSWORD`;
export const RESET_PASSWORD = `${ACTION_TYPE.API_ACTION}/RESET_PASSWORD`;
export const RESET_PASSWORD_WITH_OTP = `${ACTION_TYPE.API_ACTION}/RESET_PASSWORD_WITH_OTP`;
export const REQUEST_EMAIL_VERIFICATION_OTP = `${ACTION_TYPE.API_ACTION}/REQUEST_EMAIL_VERIFICATION_OTP`;
export const REQUEST_PHONE_VERIFICATION_OTP = `${ACTION_TYPE.API_ACTION}/REQUEST_PHONE_VERIFICATION_OTP`;
export const REQUEST_OTP = `${ACTION_TYPE.API_ACTION}/REQUEST_OTP`;
export const ATTACH_PHONE = `${ACTION_TYPE.API_ACTION}/ATTACH_PHONE`;
export const GET_EMAIL_VERIFICATION = `${ACTION_TYPE.API_ACTION}/GET_EMAIL_VERIFICATION`;
export const UPDATE_PASSWORD_BY_OTP = `${ACTION_TYPE.API_ACTION}/UPDATE_PASSWORD_BY_OTP`;
export const CLEAR_AUTH_STORE = `${ACTION_TYPE.BACKGROUND_ACTION}/CLEAR_AUTH_STORE`;

export const BACK_TO_ADMIN = `${ACTION_TYPE.API_ACTION}/BACK_TO_ADMIN`;
