export const ACTION_TYPE = {
  ROUTING_ACTION: 'ROUTING_ACTION',
  API_ACTION: 'API_ACTION',
  INTERACTION_ACTION: 'INTERACTION_ACTION',
  BACKGROUND_ACTION: 'BACKGROUND_ACTION',

  CLICK_ACTION: 'CLICK_ACTION',
  HOVER_ACTION: 'HOVER_ACTION',
  EXCEPTION_ACTION: 'EXCEPTION_ACTION',

  TRACKING_STORAGE_QUOTA: 'TRACKING_STORAGE_QUOTA',

  VERSION_DETECTATION_ACTION: 'VERSION_DETECTATION_ACTION',
  VERSION_DETECTATION_ACTION_CODE: 'VDA',

  RESPONSE_API_ACTION: 'RESPONSE_API_ACTION',
  RESPONSE_API_ACTION_CODE: 'RAA',

  API_TRACKING_BY_USER_ACTION: 'API_TRACKING_BY_USER_ACTION',
  API_TRACKING_BY_USER_ACTION_CODE: 'ATBUA',

  RESPONSE_TIME_API_ACTION: 'RESPONSE_TIME_API_ACTION',
  RESPONSE_TIME_API_ACTION_CODE: 'RTAA'
};

export const PROMISE_ACTION_TYPE = {
  PENDING: 'PENDING',
  FULFILLED: 'FULFILLED',
  REJECTED: 'REJECTED'
};

export const PENDING_TYPE = (type) => `${type}_${PROMISE_ACTION_TYPE.PENDING}`;
export const FULFILLED_TYPE = (type) => `${type}_${PROMISE_ACTION_TYPE.FULFILLED}`;
export const REJECTED_TYPE = (type) => `${type}_${PROMISE_ACTION_TYPE.REJECTED}`;
