import { ACTION_TYPE } from '../../constants/api/action.config';

export const FECTH_DATA_HOT_DEAL = `${ACTION_TYPE.API_ACTION}/FECTH_DATA_HOT_DEAL`;
export const FECTH_RECOMMENDATION_BOX = `${ACTION_TYPE.API_ACTION}/FECTH_RECOMMENDATION_BOX`;
export const FECTH_DATA_HOME_PAGE = `${ACTION_TYPE.API_ACTION}/FECTH_DATA_HOME_PAGE`;
export const FETCH_PRODUCT_BY_CATEGORY = `${ACTION_TYPE.API_ACTION}/FETCH_PRODUCT_BY_CATEGORY`;
export const UPDATE_CATEGORY_FILTER_STATE = `${ACTION_TYPE.BACKGROUND_ACTION}/UPDATE_CATEGORY_FILTER_STATE`;
export const UPDATE_PRODUCT_NAME_MOBILE = `${ACTION_TYPE.BACKGROUND_ACTION}/UPDATE_PRODUCT_NAME_MOBILE`;
export const GET_PRODUCT_DETAIL = `${ACTION_TYPE.API_ACTION}/GET_PRODUCT_DETAIL`;
export const GET_LANDING_PAGES_DATA = `${ACTION_TYPE.API_ACTION}/GET_LANDING_PAGES_DATA`;
export const FETCH_REDEEM_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_REDEEM_BOXES`;
export const FETCH_BUNDLED_ITEMS = `${ACTION_TYPE.API_ACTION}/FETCH_BUNDLED_ITEMS`;
export const FETCH_BUNDLED_PRODUCTS = `${ACTION_TYPE.API_ACTION}/FETCH_BUNDLED_PRODUCTS`;
export const ADD_WAIT_LIST = `${ACTION_TYPE.API_ACTION}/ADD_WAIT_LIST`;
export const REMOVE_FROM_WAIT_LIST = `${ACTION_TYPE.API_ACTION}/REMOVE_FROM_WAIT_LIST`;
export const FETCH_FEEDBACK_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_FEEDBACK_BOXES`;
export const FETCH_SAVING_SETS_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_SAVING_SETS_BOXES`;
export const FETCH_MAGAZINES_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_MAGAZINES_BOXES`;
export const FETCH_RELATED_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_RELATED_BOXES`;
export const FETCH_MAKEUPS = `${ACTION_TYPE.API_ACTION}/FETCH_MAKEUPS`;
export const FETCH_STORE_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_STORE_BOXES`;
export const FETCH_BOXES_CATEGORIES = `${ACTION_TYPE.API_ACTION}/FETCH_BOXES_CATEGORIES`;
export const FETCH_HOME_PRODUCT_BY_CATEGORY = `${ACTION_TYPE.API_ACTION}/FETCH_HOME_PRODUCT_BY_CATEGORY`;
export const FETCH_FEEDBACK_PICTURE = `${ACTION_TYPE.API_ACTION}/FETCH_FEEDBACK_PICTURE`;
export const FETCH_BOX_FEEDBACK_SUMMARY = `${ACTION_TYPE.API_ACTION}/FETCH_BOX_FEEDBACK_SUMMARY`;

export const FETCH_REDEEM_LATEST_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_REDEEM_LATEST_BOXES`;
export const FETCH_REDEEM_USER_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_REDEEM_USER_BOXES`;
export const FETCH_REDEEM_SPECIAL_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_REDEEM_SPECIAL_BOXES`;
export const FETCH_REVIEWABLE_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_REVIEWABLE_BOXES`;

export const CLEAR_DATA_HOT_DEAL = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_HOT_DEAL`;
export const CLEAR_DATA_PRODUCT_BY_CATEGORY = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_PRODUCT_BY_CATEGORY`;
export const CLEAR_DATA_PRODUCT_DETAIL = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_PRODUCT_DETAIL`;

export const LIKE_A_FEEDBACK = `${ACTION_TYPE.API_ACTION}/LIKE_A_FEEDBACK`;
export const UNLIKE_A_FEEDBACK = `${ACTION_TYPE.API_ACTION}/UNLIKE_A_FEEDBACK`;
