import { ACTION_TYPE } from '../action.config';

export const FETCH_LIST_MENU = `${ACTION_TYPE.API_ACTION}/FETCH_LIST_MENU`;
export const FETCH_MOBILE_HOME_MENU = `${ACTION_TYPE.API_ACTION}/FETCH_MOBILE_HOME_MENU`;
export const UPDATE_MENU_SELECTED = `${ACTION_TYPE.BACKGROUND_ACTION}/UPDATE_MENU_SELECTED`;
export const DISPLAY_MOBILE_MENU = `${ACTION_TYPE.INTERACTION_ACTION}/DISPLAY_MOBILE_MENU`;
export const DISPLAY_MOBILE_MAGAZINE_MENU = `${ACTION_TYPE.INTERACTION_ACTION}/DISPLAY_MOBILE_MAGAZINE_MENU`;
export const DISPLAY_INFO_MENU = `${ACTION_TYPE.INTERACTION_ACTION}/DISPLAY_INFO_MENU`;
export const DISPLAY_SPECIAL_DEAL_MENU = `${ACTION_TYPE.INTERACTION_ACTION}/DISPLAY_SPECIAL_DEAL_MENU`;
export const REMOVE_ACTIVE_MENU_STATUS = `${ACTION_TYPE.BACKGROUND_ACTION}/REMOVE_ACTIVE_MENU_STATUS`;
