import { ACTION_TYPE } from '../action.config';

export const FETCH_USER_BOXES_TO_FEEDBACK = `${ACTION_TYPE.API_ACTION}/FETCH_USER_BOXES_TO_FEEDBACK`;
export const FETCH_USER_FEEDBACKS = `${ACTION_TYPE.API_ACTION}/FETCH_USER_FEEDBACKS`;
export const FETCH_FEEDBACK_BY_ID = `${ACTION_TYPE.API_ACTION}/FETCH_FEEDBACK_BY_ID`;

export const ADD_FEEDBACK = `${ACTION_TYPE.API_ACTION}/ADD_FEEDBACK`;
export const EDIT_FEEDBACK = `${ACTION_TYPE.API_ACTION}/EDIT_FEEDBACK`;
export const ADD_FEEDBACK_IMAGES = `${ACTION_TYPE.API_ACTION}/ADD_FEEDBACK_IMAGES`;
export const DELETE_FEEDBACK_IMAGE = `${ACTION_TYPE.API_ACTION}/DELETE_FEEDBACK_IMAGE`;

export const SHARE_BOX_ON_FACEBOOK = `${ACTION_TYPE.API_ACTION}/SHARE_BOX_ON_FACEBOOK`;
