import { ACTION_TYPE } from '../action.config';

export const OPEN_ALERT = `${ACTION_TYPE.INTERACTION_ACTION}/OPEN_ALERT`;
export const CLOSE_ALERT = `${ACTION_TYPE.INTERACTION_ACTION}/CLOSE_ALERT`;
export const OPEN_MOBILE_SIGNIN_ALERT = `${ACTION_TYPE.INTERACTION_ACTION}/OPEN_MOBILE_SIGNIN_ALERT`;
export const CLOSE_MOBILE_SIGNIN_ALERT = `${ACTION_TYPE.INTERACTION_ACTION}/CLOSE_MOBILE_SIGNIN_ALERT`;
