import { ACTION_TYPE } from '../action.config';

export const FETCH_ACTIVITY_FEED_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_ACTIVITY_FEED_LIST`;
export const FETCH_ACTIVITY_FEED_LIST_NAVIGAATION = `${ACTION_TYPE.API_ACTION}/FETCH_ACTIVITY_FEED_LIST_NAVIGAATION`;
export const FETCH_ACTIVITY_FEED_NEWEST = `${ACTION_TYPE.API_ACTION}/FETCH_ACTIVITY_FEED_NEWEST`;
export const FETCH_ACTIVITY_FEED_DETAIL = `${ACTION_TYPE.API_ACTION}/FETCH_ACTIVITY_FEED_DETAIL`;

export const FETCH_ACTIVITY_FEED_COMMENT_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_ACTIVITY_FEED_COMMENT_LIST`;
export const UPDATE_ACTIVITY_FEED_COMMENT = `${ACTION_TYPE.API_ACTION}/UPDATE_ACTIVITY_FEED_COMMENT`;
export const DELETE_ACTIVITY_FEED_COMMENT = `${ACTION_TYPE.API_ACTION}/DELETE_ACTIVITY_FEED_COMMENT`;
export const ADD_ACTIVITY_FEED_COMMENT = `${ACTION_TYPE.API_ACTION}/ADD_ACTIVITY_FEED_COMMENT`;
export const ADD_ACTIVITY_FEED_LIKE = `${ACTION_TYPE.API_ACTION}/ADD_ACTIVITY_FEED_LIKE`;
export const DELETE_ACTIVITY_FEED_LIKE = `${ACTION_TYPE.API_ACTION}/DELETE_ACTIVITY_FEED_LIKE`;

export const GET_COLLECTION = `${ACTION_TYPE.API_ACTION}/GET_COLLECTION`;
export const GET_COLLECTION_DETAIL = `${ACTION_TYPE.API_ACTION}/GET_COLLECTION_DETAIL`;

export const FETCH_COMMUNITY_HASHTAGS = `${ACTION_TYPE.API_ACTION}/FETCH_COMMUNITY_HASHTAGS`;
export const FETCH_COMMUNITY_HASHTAG_FEEDS = `${ACTION_TYPE.API_ACTION}/FETCH_COMMUNITY_HASHTAG_FEEDS`;

export const FETCH_COMMUNITY_HOT_BOXES = `${ACTION_TYPE.API_ACTION}/FETCH_COMMUNITY_HOT_BOXES`;
export const FETCH_COMMUNITY_GOOD_SALE = `${ACTION_TYPE.API_ACTION}/FETCH_COMMUNITY_GOOD_SALE`;
export const FETCH_COMMUNITY_TOP_REVIEW = `${ACTION_TYPE.API_ACTION}/FETCH_COMMUNITY_TOP_REVIEW`;
export const FETCH_COMMUNITY_TOP_LIKED = `${ACTION_TYPE.API_ACTION}/FETCH_COMMUNITY_TOP_LIKED`;

export const CLEAR_DATA_COMMUNITY_HASHTAGS = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_COMMUNITY_HASHTAGS`;
export const CLEAR_DATA_COMMUNITY_HASHTAG_FEEDS = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_COMMUNITY_HASHTAG_FEEDS`;

export const CLEAR_DATA_ACTIVITY_FEED_LIST = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_ACTIVITY_FEED_LIST`;
export const CLEAR_DATA_ACTIVITY_FEED_COMMENT_LIST = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_ACTIVITY_FEED_COMMENT_LIST`;
export const CLEAR_DATA_COLLECTION = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_COLLECTION`;
export const CLEAR_DATA_ACTIVITY_FEED_DETAIL = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_ACTIVITY_FEED_DETAIL`;

export const GET_USER_COMMUNITY_PROFILE = `${ACTION_TYPE.API_ACTION}/GET_USER_COMMUNITY_PROFILE`;
