import { ACTION_TYPE } from '../action.config';

export const FETCH_USER_ADDRESS_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_USER_ADDRESS_LIST`;
export const ADD_USER_ADDRESS = `${ACTION_TYPE.API_ACTION}/ADD_USER_ADDRESS`;
export const EDIT_USER_ADDRESS = `${ACTION_TYPE.API_ACTION}/EDIT_USER_ADDRESS`;
export const DELETE_USER_ADDRESS = `${ACTION_TYPE.API_ACTION}/DELETE_USER_ADDRESS`;
export const SAVE_ADDRESS_SELECTED = `${ACTION_TYPE.API_ACTION}/SAVE_ADDRESS_SELECTED`;
