import { IProps, IState } from './model';
import * as VARIABLE from '../../../style/variable';

export const DEFAULT_PROPS = {
  name: 'logo',
  style: {
    position: 'static',
    width: 30,
    height: 30,
    color: VARIABLE.colorPink,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center'
  },
  innerStyle: {
    width: '100%',
    height: '100%'
  },
  className: '',
  onClick: () => {},
  onEnter: () => {},
  onLeave: () => {}
} as IProps;

export const INITIAL_STATE = {
  hovering: false,
  defaultIcon: 'logo-line',
  listIcon: [
    'logo',
    'logo-line',
    'logo-text',
    'caret-down',
    'angle-up',
    'angle-down',
    'angle-left',
    'angle-right',
    'arrow-up',
    'arrow-down',
    'arrow-left',
    'arrow-right',
    'trash',
    'search',
    'cart',
    'cart-line',
    'heart',
    'heart-line',
    'heart-full',
    'play',
    'time',
    'star',
    'star-line',
    'star-half',
    'star-light',
    'dollar',
    'deliver',
    'refresh',
    'menu',
    'close',
    'facebook',
    'instagram',
    'youtube',
    'pinterest',
    'plus',
    'minus',
    'feed',
    'gift',
    'bell',
    'user',
    'user-plus',
    'info',
    'related',
    'message',
    'message-faq',
    'message-heart',
    'danger',
    'error',
    'success',
    'check',
    'check-bold',
    'edit',
    'selfie',
    'camera',
    'like',
    'like-full',
    'sign-in',
    'sign-out',
    'tag-price',
    'percent',
    'magazine',
    'store',
    'book',
    'call',
    'email',
    'fly',
    'circle',
    'copy',
    'bookmark',
    'bookmark-line',
    'verification',
    'filter',
    'app',
    'eye',
    'map-marker',
    'cosmetic',
    'picture',
    'hash',
    'half-lighting',
    'paper-plane',
    'shopping-bag',
    'heart-box',
    'rating-stage',
    'invite-email',
    'next-link',
    'color-deliver',
    'color-store',
    'color-money',
    'color-visa',
    'color-atm',
    'color-banking',
    'color-momo',
    'color-rocket',
    'color-shopping',
    'color-community',
    'color-magazine',
    'color-sign-in',
    'color-unboxing',
    'color-star',
    'box-empty',
    'messager',
    'brand-google',
    'zalo'
  ]
} as IState;
