import { ACTION_TYPE } from '../action.config';

export const FETCH_BRAND_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_BRAND_LIST`;
export const FETCH_PRODUCT_BY_BRAND_ID = `${ACTION_TYPE.API_ACTION}/FETCH_PRODUCT_BY_BRAND_ID`;
export const CLEAR_DATA_PRODUCT_BY_BRAND_ID = `${ACTION_TYPE.BACKGROUND_ACTION}/CLEAR_DATA_PRODUCT_BY_BRAND_ID`;
