import { ACTION_TYPE } from '../action.config';

export const GET_REPORTS_FEATURES = `${ACTION_TYPE.API_ACTION}/GET_REPORTS_FEATURES`;
export const FEEDBACK_REPORTS_FEATURES = `${ACTION_TYPE.API_ACTION}/FEEDBACK_REPORTS_FEATURES`;
