export const MoEEvents = Object.freeze({
  LOGIN: 'login',
  SIGN_UP: 'sign_up',
  LOGOUT: 'logout',
  VIEW_CONTENT: 'view_content',
  VIEW_CONTENT_LIST: 'view_content_list',
  VIEW_MAGAZINE: 'view_magazine',
  COMPLETE_MAGAZINE: 'complete_magazine',
  ADD_TO_CART: 'add_to_cart',
  REMOVE_FROM_CART: 'remove_from_cart',
  VIEW_CART: 'view_cart',
  BEGIN_CHECKOUT: 'begin_checkout',
  CANCEL_ORDER: 'cancel_order',
  SEARCH: 'search',
  RATE_PRODUCT: 'rate_product',
  PURCHASE: 'purchase',
  ADD_TO_WISHLIST: 'add_to_wishlist',
  REMOVE_FROM_WISHLIST: 'remove_from_wishlist',
  ADD_TO_WAIT_LIST: 'add_to_wait_list',
  REMOVE_FROM_WAIT_LIST: 'remove_from_wait_list',
  SHARE: 'share',
  TUTORIAL_BEGIN: 'tutorial_begin',
  TUTORIAL_COMPLETE: 'tutorial_complete'
});

export const MoEAttributes = Object.freeze({
  CONTENT_TYPE: 'content_type',
  CONTENT_ID: 'content_id',
  CONTENT_NAME: 'content_name',
  CONTENTS: 'contents',
  PRICE: 'price',
  TOTAL_PRICE: 'total_price',
  CURRENCY: 'currency',
  QUANTITY: 'quantity',
  PRODUCT_CATEGORY: 'product_category',
  PRODUCT_URL: 'product_url',
  PRODUCT_IMAGE_URL: 'product_image_url',
  MAGAZINE_CATEGORY: 'magazine_category',
  SEARCH_TERM: 'search_term',
  RATING_VALUE: 'rating_value',
  MEMBER: 'member',
  SHIPPING: 'shipping',
  COUPON: 'coupon',
  METHOD: 'method',
  LIXICOIN: 'lixicoin',
  PROVIDER: 'provider',
  USER_ID: 'user_id',
  EMAIL: 'email',
  SCROLL_PERCENTAGE: 'scroll_percentage'
});
