import { ACTION_TYPE } from '../action.config';

export const FETCH_ORDER = `${ACTION_TYPE.API_ACTION}/FETCH_ORDER`;
export const UPDATE_ODER = `${ACTION_TYPE.API_ACTION}/UPDATE_ODER`;
export const FETCH_CANCEL_ORDER_REASON = `${ACTION_TYPE.API_ACTION}/FETCH_CANCEL_ORDER_REASON`;
export const CANCEL_ORDER = `${ACTION_TYPE.API_ACTION}/CANCEL_ORDER`;
export const CONFIRM_ORDER_RECEIVED = `${ACTION_TYPE.API_ACTION}/CONFIRM_ORDER_RECEIVED`;
export const GET_BIRTHDAY_ORDER = `${ACTION_TYPE.API_ACTION}/GET_BIRTHDAY_ORDER`;
