import { ACTION_TYPE } from '../action.config';

export const OPEN_SHARED_MODAL = `${ACTION_TYPE.INTERACTION_ACTION}/OPEN_SHARED_MODAL`;
export const UPDATE_SHARED_MODAL = `${ACTION_TYPE.INTERACTION_ACTION}/UPDATE_SHARED_MODAL`;
export const CLOSE_SHARED_MODAL = `${ACTION_TYPE.INTERACTION_ACTION}/CLOSE_SHARED_MODAL`;
export const CLOSE_ALL_SHARED_MODAL = `${ACTION_TYPE.INTERACTION_ACTION}/CLOSE_ALL_SHARED_MODAL`;
