import { ACTION_TYPE } from '../action.config';

export const PUSH_ERROR = `${ACTION_TYPE.INTERACTION_ACTION}/PUSH_ERROR`;
export const POP_ERROR = `${ACTION_TYPE.INTERACTION_ACTION}/POP_ERROR`;
export const CLEAR_ERRORS = `${ACTION_TYPE.INTERACTION_ACTION}/CLEAR_ERRORS`;
