import { ACTION_TYPE } from '../action.config';

export const FETCH_LIVE_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_LIVE_LIST`;
export const GET_LIVE_DETAIL = `${ACTION_TYPE.API_ACTION}/GET_LIVE_DETAIL`;

export const FETCH_LIVE_COMMENT_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_LIVE_COMMENT_LIST`;
export const FETCH_LIVE_REPLIES_COMMENT_LIST = `${ACTION_TYPE.API_ACTION}/FETCH_LIVE_REPLIES_COMMENT_LIST`;
export const CREATE_LIVE_COMMENT = `${ACTION_TYPE.BACKGROUND_ACTION}/CREATE_LIVE_COMMENT`;

export const UPDATE_DATA_FROM_SOCKET = `${ACTION_TYPE.BACKGROUND_ACTION}/UPDATE_DATA_FROM_SOCKET`;
export const DISPLAY_LIVE_BACKGROUND = `${ACTION_TYPE.BACKGROUND_ACTION}/DISPLAY_LIVE_BACKGROUND`;
