import { ACTION_TYPE } from '../action.config';

export const UPDATE_URL_PARAMS = `${ACTION_TYPE.BACKGROUND_ACTION}/UPDATE_URL_PARAMS`;
export const UPDATE_PRIVATE_MODE = `${ACTION_TYPE.BACKGROUND_ACTION}/UPDATE_PRIVATE_MODE`;
export const UPDATE_AB_TESTING_MODE = `${ACTION_TYPE.BACKGROUND_ACTION}/UPDATE_AB_TESTING_MODE`;
