import {
  ROUTING_AUTH_FORGOT_PASSWORD,
  ROUTING_AUTH_SIGN_IN,
  ROUTING_AUTH_SIGN_UP,
  ROUTING_CHECK_OUT
} from '../../routings/path';

export const BLACK_LIST_CONTAINER_SPLASH_BANNER = [
  ROUTING_AUTH_SIGN_IN,
  ROUTING_AUTH_SIGN_UP,
  ROUTING_AUTH_FORGOT_PASSWORD,
  ROUTING_CHECK_OUT
];
