import * as ROUTINGS from '../../routings/path';

export const PROMO_POPUP_ROUTE_BLACKLIST = [
  ROUTINGS.ROUTING_GAME,
  ROUTINGS.ROUTING_CHECK_OUT_PATH,
  ROUTINGS.ROUTING_AUTH_SIGN_IN,
  ROUTINGS.ROUTING_AUTH_SIGN_UP,
  ROUTINGS.ROUTING_AUTH_CHECKOUT_FAST_TRACK,
  ROUTINGS.ROUTING_AUTH_FORGOT_PASSWORD,
  ROUTINGS.ROUTING_AUTH_VERIFY_PHONE,
  ROUTINGS.ROUTING_AUTH_PHONE_REGISTERED,
  ROUTINGS.ROUTING_AUTH_LOGIN_UNCONFIRMED_PHONE_PROMPT,
  ROUTINGS.ROUTING_AUTH_ATTACH_PHONE_STEP_1,
  ROUTINGS.ROUTING_AUTH_ATTACH_PHONE_STEP_2,
  ROUTINGS.ROUTING_AUTH_CONNECT_FACEBOOK,
  ROUTINGS.ROUTING_AUTH_CONNECT_GOOGLE
];

export const MESSENGER_PLUGIN_BLACKLIST = [
  ROUTINGS.ROUTING_PRODUCT_DETAIL,
  ROUTINGS.ROUTING_CHECK_OUT,
  ROUTINGS.ROUTING_CHECK_OUT_PAYMENT,
  ROUTINGS.ROUTING_CHECK_OUT_SUCCESS,
  ROUTINGS.ROUTING_AUTH_SIGN_IN,
  ROUTINGS.ROUTING_AUTH_SIGN_UP,
  ROUTINGS.ROUTING_AUTH_CHECKOUT_FAST_TRACK,
  ROUTINGS.ROUTING_AUTH_RESET_PASSWORD,
  ROUTINGS.ROUTING_AUTH_FORGOT_PASSWORD,
  ROUTINGS.ROUTING_MOBILE_BRAND_PATH,
  ROUTINGS.ROUTING_SPECIAL_DEAL_DETAIL,
  ROUTINGS.ROUTING_USER,
  ROUTINGS.ROUTING_GAME,
  ROUTINGS.ROUTING_GAME_BEAUTY_HUNTER,
  ROUTINGS.ROUTING_GAME_BEAUTY_HUNTER_PLAY,
  ROUTINGS.ROUTING_GAME_BEAUTY_HUNTER_RESULT
];

/**
 * NOTE: All the routes are expected to be in lowercase
 */
export const AUTHENTICATOR_ROUTES = [
  ROUTINGS.ROUTING_AUTH_SIGN_IN,
  ROUTINGS.ROUTING_AUTH_SIGN_UP,
  ROUTINGS.ROUTING_AUTH_CHECKOUT_FAST_TRACK,
  ROUTINGS.ROUTING_AUTH_FORGOT_PASSWORD,
  ROUTINGS.ROUTING_AUTH_VERIFY_PHONE,
  ROUTINGS.ROUTING_AUTH_PHONE_REGISTERED,
  ROUTINGS.ROUTING_AUTH_LOGIN_UNCONFIRMED_PHONE_PROMPT,
  ROUTINGS.ROUTING_AUTH_ATTACH_PHONE_STEP_1,
  ROUTINGS.ROUTING_AUTH_ATTACH_PHONE_STEP_2
];
