import * as ROUTINGS from '../../routings/path';

export const PRIVATE_MODE_URL = [ROUTINGS.ROUTING_HALIO_PRIVATE_ACCESSS_TRADE];

export const IGNORE_DETECT_PRIVATE_MODE_URL = [
  ROUTINGS.ROUTING_CHECK_OUT_PATH,
  ROUTINGS.ROUTING_CHECK_OUT,
  ROUTINGS.ROUTING_CHECK_OUT_PAYMENT,
  ROUTINGS.ROUTING_CHECK_OUT_SUCCESS
];
