export const PURCHASE_TYPE = {
  NORMAL: 0,
  REDEEM: 1,
  SAMPLE: 2,
  GIFT: 3,
  ADDON: 4
};
export type PurchaseTypeType = (typeof PURCHASE_TYPE)[keyof typeof PURCHASE_TYPE];

export const DISPLAY_ORDER = [
  PURCHASE_TYPE.NORMAL,
  PURCHASE_TYPE.ADDON,
  PURCHASE_TYPE.REDEEM,
  PURCHASE_TYPE.GIFT,
  PURCHASE_TYPE.SAMPLE
];

export const FREE_PURHASE_TYPE = [PURCHASE_TYPE.GIFT, PURCHASE_TYPE.SAMPLE];
