import { ACTION_TYPE } from '../action.config';

export const GET_EXPERT_INFO = `${ACTION_TYPE.API_ACTION}/GET_EXPERT_INFO`;
export const FETCH_PRODUCT_BY_EXPERT = `${ACTION_TYPE.API_ACTION}/FETCH_PRODUCT_BY_EXPERT`;

export const CLEAR_DATA_EXPERT_INFO = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_EXPERT_INFO`;
export const CLEAR_DATA_PRODUCT_BY_EXPERT = `${ACTION_TYPE.API_ACTION}/CLEAR_DATA_PRODUCT_BY_EXPERT`;
