import { ACTION_TYPE } from '../action.config';

export const SET_MAINTENANCE_MODE = `${ACTION_TYPE.INTERACTION_ACTION}/SET_MAINTENANCE_MODE`;
export const CLEAR_MAINTENANCE_MODE = `${ACTION_TYPE.INTERACTION_ACTION}/CLEAR_MAINTENANCE_MODE`;
